services:
  - docker

before_install:
  - git clone https://github.com/mandrewcito/signalrcore-containertestservers containers
  - pip install -r requirements.txt

install:
  - cd containers
  - docker-compose up -d
  - docker ps
  - cd ..
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6" 
  - "3.7"
  - "3.8"
# command to run tests
script:
- python -m unittest discover -s test/ -p "*_test.py"
